### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by Cholmondely-of-Digebiti** [tsoj/himsn#3]
Should we rename the Alpha/Beta/Gamma versions here, so we don't end up confusing the Beta version of the Alpha version with an Alpha version of the Beta version. Or am I being inane?

Gimi renamed them as Stages One, Two and Three in his later description:

**Stage one (Eye candy only)**
- Navy ships based on core ships using models form Griff and Smivs ships.
- 2 Types of stations (1 x Navy HQ) (8 x Navy regional HQ's, one for each galaxy).
- Would feature a set of Navy ships based on Griff and /Smivs ships with Navy colours and markings. (3 models, 5 different types. Asp, Sidewinder, Anaconda missile corvette, Anaconda logistics ship, and an Asp Courier type.).
- Ship behaviour would be adapted to give a distinct military behaviour (I have some ideas on rules for this, and it would probably require the new AI features in 1.77 if at all possible)

**Stage 2 (More eye candy, capital ships and battles, prepare for missions in stage 3)**
- Few more stations (2 x Navy ship yard type station, 8 x Intelligence HQ stations in hidden systems)
- Stage two would see the introduction of two (or maybe just one) classes of carriers.
- I would like to introduce some extremely rare intelligence/Special Operations type ships including the production model of the Constrictor in preparation for missions in stage three.
- Introduction of HIMSN Fleet day.
- Rare battles with the Thargoids in Intergalactic space.
- Further AI development would be needed to cater for these shy intelligence guys.

**Stage 3 (Missions)**
Missions. Details are a lot more sketchy here.
Ideas include courier and delivery missions to some very odd places, sting operations where you are asked to pilot a constrictor.

**Some main design thoughts are:**

The Navy are not Police and will not behave like Police. This means that they will not attack criminals and in general they will not intervene in a fight, but they will report criminal acts (piracy). I know that historically in RL counter piracy has been a Navy task, but I find that this fits better in Oolite.
The navy tries to stay out of your way, and normally you won't see them unless you try to find them. They don't like to show off, except for that one day a year that is.
Ships are generally few and far between, but better than their civilian counterparts, and always fully equipped with an "Iron Ass". Quality over quantity principle.
The military in general have no concept of fighting fair. They will follow the rules given to them, but will come back at you with all they have if you provoke them. Concentration of fire and overkill are two thoughts here. They never operate alone is another (Except the intel/specops guys that is).

**Comment by tsoj** [comment]
> so we don't end up confusing the Beta version of the Alpha version with an Alpha version of the Beta version.

I agree, it's a bit confusing. Nothing would be lost dropping the Alpha-Beta-Gamma naming scheme. I will update the README.
